---
name: Continuous Integration Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.build/**'
      - '.github/workflows/deployment.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [
        {'version': '8', 'source': 'releases'},
        {'version': '11', 'source': 'releases'},
        {'version': '14', 'source': 'releases'}
        ]
    name: Build with Java ${{ matrix.java.version }} (OpenJDK)
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - uses: actions/checkout@v2
      - uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: ${{ matrix.java.version }}
          source: ${{ matrix.java.source }}
      - name: Build with Maven
        run: mvn -B clean verify

  java15:
    runs-on: ubuntu-20.04
    name: Build with Java 15 (Zulu)
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - uses: actions/checkout@v2
      - name: Install JDK 15
        uses: actions/setup-java@v1.4.2
        with:
          java-version: '15-ea'
          architecture: x64
      - name: Build with Maven
        run: mvn -B clean verify

  quality:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - uses: actions/checkout@v2
      - name: Install JDK 1.8
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 8
      - name: Coverage and Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_LOGIN }}
        run: |
          mvn verify -Pcoverage
          mvn sonar:sonar \
            -Dsonar.projectKey=smallrye_smallrye-mutiny \
            -Dsonar.projectName="SmallRye Mutiny" \
            -Dsonar.organization=smallrye \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_LOGIN \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco.xml
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
