---
name: Pull Request Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [
          {'version': '8', 'source': 'releases'},
          {'version': '11', 'source': 'releases'},
          {'version': '14', 'source': 'releases'}
        ]
    name: Build with Java ${{ matrix.java.version }}
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - uses: actions/checkout@v2
      - name: Install JDK ${{ matrix.java.version }} (OpenJDK)
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: ${{ matrix.java.version }}
          source: ${{ matrix.java.source }}
      - name: Build with Maven
        run: mvn -B clean verify -Pcoverage
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
  java15:
      runs-on: ubuntu-20.04
      name: Build with Java 15
      steps:
        - uses: actions/cache@v2
          with:
            path: ~/.m2/repository
            key: maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              maven-
        - uses: actions/checkout@v2
        - name: Install JDK 15 (Zulu)
          uses: actions/setup-java@v1.4.2
          with:
            java-version: '15-ea'
            architecture: x64
        - name: Build with Maven
          run: mvn -B clean verify

