name: Deployment
on: [deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 1.8
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: 'openjdk8'
      - name: 'Run deployment script for ${{ github.event.deployment.environment }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_SETTINGS: ${{ secrets.MVN_SETTINGS }}
          SMALLRYE_SIGNATURE: ${{ secrets.GPG_SIGNATURE }}
        run: |
          sudo apt-get update -o Dir::Etc::sourcelist="sources.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
          sudo apt-get install -y gnupg2
          chmod +x .build/deploy.sh .build/decrypt-secrets.sh
          .build/decrypt-secrets.sh
          .build/deploy.sh ${{ github.event.deployment.environment }}